import { Octokit } from '@octokit/rest';
import { GeneratedFile } from '../agents/generator';

function slugifyPrompt(prompt: string, maxLen = 45): string {
  return prompt
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .slice(0, maxLen)
    .replace(/-+$/, '');
}

/**
 * Try to extract an explicit repo name from a prompt like
 * "create a repo named my-app" or 'called "my-app"'.
 * Falls back to slugifying the full prompt.
 */
function extractRepoName(prompt: string, requestId: string): string {
  const match = prompt.match(
    /(?:repo(?:sitory)?|project)\s+(?:named?|called)\s+["']?([a-z0-9][a-z0-9._-]{0,38}[a-z0-9])["']?/i
  ) ?? prompt.match(/["']([a-z0-9][a-z0-9._-]{0,38}[a-z0-9])["']/i);
  if (match) return match[1].toLowerCase();
  const slug = slugifyPrompt(prompt, 40);
  return slug || `autodev-${requestId.slice(0, 8)}`;
}

export async function pushToGitHub(
  requestId:    string,
  prompt:       string,
  files:        GeneratedFile[],
  targetRepo:   { owner: string; repo: string } | undefined,
  githubToken?: string
): Promise<string> {
  const token   = githubToken ?? process.env.GITHUB_TOKEN!;
  const octokit = new Octokit({ auth: token });

  if (targetRepo) {
    // Create a branch and open a PR on the existing repo
    return createBranchAndPR(octokit, requestId, prompt, files, targetRepo.owner, targetRepo.repo);
  }

  // New repo: create it and push directly to default branch
  const owner    = process.env.GITHUB_ORG || (await getAuthenticatedUser(octokit));
  const repoName = extractRepoName(prompt, requestId);
  const repo     = await createRepo(octokit, owner, repoName);
  for (const file of files) {
    await pushFile(octokit, owner, repoName, file.path, file.content);
  }
  return repo.html_url;
}

async function createBranchAndPR(
  octokit:   Octokit,
  requestId: string,
  prompt:    string,
  files:     GeneratedFile[],
  owner:     string,
  repo:      string
): Promise<string> {
  // Get default branch + its HEAD SHA
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const baseBranch = repoData.default_branch;
  const { data: ref } = await octokit.git.getRef({ owner, repo, ref: `heads/${baseBranch}` });
  const baseSha = ref.object.sha;

  // Create a descriptive branch name
  const slug       = slugifyPrompt(prompt);
  const branchName = `autodev/${slug}-${requestId.slice(0, 8)}`;
  await octokit.git.createRef({
    owner, repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });

  // Push all files to the new branch
  for (const file of files) {
    await pushFile(octokit, owner, repo, file.path, file.content, branchName);
  }

  // Open a PR to the default branch
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `AutoDev AI: ${prompt.slice(0, 72)}`,
    head:  branchName,
    base:  baseBranch,
    body: [
      '> This PR was automatically generated by **AutoDev AI**.',
      '',
      `**Prompt:** ${prompt}`,
      `**Request ID:** \`${requestId}\``,
    ].join('\n'),
  });

  return pr.html_url;
}

async function getAuthenticatedUser(octokit: Octokit): Promise<string> {
  const { data } = await octokit.users.getAuthenticated();
  return data.login;
}

async function createRepo(octokit: Octokit, owner: string, name: string): Promise<{ html_url: string }> {
  if (process.env.GITHUB_ORG) {
    const { data } = await octokit.repos.createInOrg({
      org: owner, name,
      description: 'Generated by AutoDev AI',
      private: false, auto_init: true,
    });
    return { html_url: data.html_url };
  }
  const { data } = await octokit.repos.createForAuthenticatedUser({
    name,
    description: 'Generated by AutoDev AI',
    private: false, auto_init: true,
  });
  return { html_url: data.html_url };
}

async function pushFile(
  octokit:    Octokit,
  owner:      string,
  repo:       string,
  filePath:   string,
  content:    string,
  branch?:    string
): Promise<void> {
  const encoded = Buffer.from(content, 'utf8').toString('base64');

  let sha: string | undefined;
  try {
    const { data } = await octokit.repos.getContent({
      owner, repo, path: filePath,
      ...(branch ? { ref: branch } : {}),
    });
    if (!Array.isArray(data) && data.type === 'file') sha = data.sha;
  } catch { /* file doesn't exist yet */ }

  await octokit.repos.createOrUpdateFileContents({
    owner, repo,
    path:    filePath,
    message: `feat: ${filePath} [AutoDev AI]`,
    content: encoded,
    sha,
    ...(branch ? { branch } : {}),
  });
}
