import { Octokit } from '@octokit/rest';
import { GeneratedFile } from '../agents/generator';

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

export async function pushToGitHub(
  requestId:   string,
  files:       GeneratedFile[],
  targetRepo?: { owner: string; repo: string }
): Promise<string> {
  let owner: string;
  let repoName: string;
  let repoUrl: string;

  if (targetRepo) {
    // Commit to an existing repo
    owner    = targetRepo.owner;
    repoName = targetRepo.repo;
    const { data } = await octokit.repos.get({ owner, repo: repoName });
    repoUrl = data.html_url;
  } else {
    // Create a new repo
    owner    = process.env.GITHUB_ORG ?? (await getAuthenticatedUser());
    repoName = `autodev-${requestId.slice(0, 8)}`;
    const repo = await createRepo(owner, repoName);
    repoUrl = repo.html_url;
  }

  // Push files via Contents API (one request per file)
  for (const file of files) {
    await pushFile(owner, repoName, file.path, file.content);
  }

  return repoUrl;
}

async function getAuthenticatedUser(): Promise<string> {
  const { data } = await octokit.users.getAuthenticated();
  return data.login;
}

async function createRepo(owner: string, name: string): Promise<{ html_url: string }> {
  const isOrg = !!process.env.GITHUB_ORG;

  if (isOrg) {
    const { data } = await octokit.repos.createInOrg({
      org: owner, name,
      description: 'Generated by AutoDev AI',
      private: false, auto_init: true,
    });
    return { html_url: data.html_url };
  }

  const { data } = await octokit.repos.createForAuthenticatedUser({
    name,
    description: 'Generated by AutoDev AI',
    private: false, auto_init: true,
  });
  return { html_url: data.html_url };
}

async function pushFile(owner: string, repo: string, filePath: string, content: string): Promise<void> {
  const encoded = Buffer.from(content, 'utf8').toString('base64');

  let sha: string | undefined;
  try {
    const { data } = await octokit.repos.getContent({ owner, repo, path: filePath });
    if (!Array.isArray(data) && data.type === 'file') sha = data.sha;
  } catch { /* file doesn't exist yet */ }

  await octokit.repos.createOrUpdateFileContents({
    owner, repo,
    path:    filePath,
    message: `feat: add ${filePath} [AutoDev AI]`,
    content: encoded,
    sha,
  });
}
